### ISSUE TITLE
Linux User Run These

### ISSUE THREAD

**Issue by ItsJustMeChris** [r-webdev/discord-bot#20]
I cannot run these because they install linux binaries, and I'm on windows.  (: 👍 

`npm i ffmpeg-binaries`
`npm i opusscript`

>>>>MAKE SURE `lzma-native` INSTALLS VERSION 4.0.3 OTHER VERSIONS DO NOT WORK WITH NODE JS 11 (LATEST VERSION OF NODE) <<<<

Yes, the capitals were important, I spent far longer than I wanted to tonight trying to figure out how to make this work on node 11 👎

**Comment by ItsJustMeChris** [comment]
opusscript should be development only, 
`npm i node-opus` will have better performance, but that's a lot more work to install. 

When the bot goes production whoever sets it up will need to figure it out. 🥇

**Comment by gmemstr** [comment]
D: Guess I'll figure this out this weekend
