### ISSUE TITLE
Implement database for persistent storage

### ISSUE THREAD

**Issue by ItsJustMeChris** [r-webdev/discord-bot#4]
I am thinking that a light weight database that uses flat files may be the best approach to make this usable out of the box for easier community contribution, but honestly anything works. This is needed for some persistence when looking at modules like:

User Management
Ranks
Command Permissions
Command Prefix Customization

**Comment by gmemstr** [comment]
Going with MonoDB/Mongoose for this, w/ schemas. Configuration goes into .env as well - should write up some docs for this stuff.

**Comment by ItsJustMeChris** [comment]
This is done.
